server:
  name: "explorer"
  testnet: true
  rpc_listen: ":8336"
chain:
  url: "http://127.0.0.1:18334"
  username: "root"
  password: "root"
db:
  mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "root"
    db: "explorer"
  indexer:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "root"
    db: "cins"
origins:
  - ".*"