server:
  name: "explorer"
  testnet: true
  rpc_listen: ":8336"
  pprof: false
  prometheus: false
chain:
  url: "http://127.0.0.1:18334"
  username: "root"
  password: "root"
  start_height: 2580609
db:
  mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "root"
    db: "explorer"
  indexer:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "root"
    db: "cins"
sentry:
  dsn: ""
  traces_sample_rate: 1.0
origins:
  - ".*"